apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
     matchLabels:
         app: frontend-web-server
  template:
    metadata:
      labels:
        app: frontend-web-server
        version: "1.0"
    spec:
      containers:
        - name: frontend-web-server
          image: replace
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      serviceAccountName: default
      imagePullSecrets:
           - name: regcred


---

apiVersion: v1
kind: Service
metadata:
 name: frontend-web-server
spec:
 type: NodePort
 selector:
   app: frontend-web-server
   version: "1.0"
 ports:
 - port: 3000
   targetPort: 3000
   protocol: TCP
   nodePort: 30020
